#!/bin/bash

#
<<'COMMENTS'

Script by Alex Alduk S3437526

This script initiates and installs the the Linux Kernel for the Raspberry Pi 4

The first variable is the working directory - NO

Input working directory as variable - NO
Input IP address when running script...


COMMENTS

#Variables
declare dir=$(pwd)"/tmp"
declare displayIP=$1":0.0"
declare gitRepo="git@github.com:s3437526/USAP_Assignment2.git"

#*************************************************************************************
#Dummmy test print! - remove!
#*************************************************************************************
printf "Entered IP address is :$displayIP\n"

#Check for input flags - if the first variable (local IP address) is null then exit
if [ -z "$1" ] ;
then
	printf "There has been no IP address input. Please ensure you enter your local IP address before continuting.\nExiting..."
exit
fi


#Install pre-requisites for kernel download
echo "Installing dependancies..."
apt install raspberrypi-kernel-headers build-essential bc git wget bison flex libssl-dev make

#Crete temporary clone directory for setup
#If the directory exists then warn the user to back it up as it would get deleted on completion of the script
if [ -d $dir ] ;
then
	printf "\nThe $dir directory already exists.\nPlease ensure it is backed up as it will be deleted on completion of this process.\nExiting...\n"
exit
fi

cd $dir
mkdir tmp
cd tmp

#Convert directory to git directory
git init
git checkout -b Requirement_5

#Download latest linux kernel
echo "Fetching the latest Rasbperry Pi Kernel mirror"
git clone --depth=1 https://github.com/raspberrypi/linux

#Select kernel for Rapberry Pi 4
echo "Setting Kernel to Rasberry Pi 4"
KERNEL=kernel7l

echo "Making bcm2711_defconfig..."
cd linux
make bcm2711_defconfig

echo "Installing qt5..."
apt-get install qt5-\*-dev

printf "\nEnsuring X11 screen is exported as localhost. Please ensure X11 is being forwarded otherwise this process will fail. \nCurrent display is exported as $displayIP. If this is not the same this process will fail. Be sure to export the correct display with an instance of X server running. \nResuming in 10 seconds..."
sleep 10
export DISPLAY=$displayIP

echo "Making Xconfig"
#cd linux
make xconfig || { printf "There was an error with getting Xconfig running. Please check that you have X11 installed, X11 forwarded and a correct local (client computer) IP address.";  exit ; }

echo "Setting image to run on 4 cores..."
sudo make -j4 zImage modules dtbs

echo "Installing..."
sudo make modules_install 
sudo cp arch/arm/boot/dts/*.dtb /boot/ 
sudo cp arch/arm/boot/dts/overlays/*.dtb* /boot/overlays/ 
sudo cp arch/arm/boot/dts/overlays/README /boot/overlays/

echo "Copying architecture to Kernel image..."
sudo cp arch/arm/boot/zImage /boot/$KERNEL.img

#Delete temporary folder
#echo "Deleting temporary folder..."
#sudo rm -r /home/alx/tmp
