#!/bin/bash

# Script by Aleksandar Alduk S3437526

# This script is designed to automate the installation
# of the manual page for the build_kernel script.

# Global variables/definitions
declare CP=/bin/cp
declare GZIP=/bin/gzip
declare SUCCESS=0
declare FAILURE=1

# Install the manual page - using input parameters as respective manual pages
function install_manpage () {
	
	# Local variables
	local man_src="manual"
	local man_dest="/usr/share/man/man1/"
	local student_dir="\"$HOME\"/s3437526_A2/"

	# Copy the manpage to the shared man1 page directory - if this 
	# fails then notify the user and exit
	echo "Copying manual page entry to manuals directory..."
	if ! sudo "$CP" "$student_dir""$man_src"/"$1" "$man_dest""$1" ; then
		printf "%s" "Error: unable to copy manual page for the "
		printf "%s\n" "script to the manuals directory."
		printf "%s" "Please check that the file \"$1\""
		printf "%s\n" " exists in the \"$man_src\" directory."
		printf "%s\n" "Exiting..."
		printf "\n"
		exit "$FAILURE"
	fi
	echo "Done."

	# Compress the manpage document to a gzip format for use with man - 
	# if it fails, report to the user and exit
	echo "Compressing file for use with the manual system..."
	if ! sudo "$GZIP" "$man_dest""$1" ; then
		printf "%s" "Error: unable to compress \"$1\" "
		printf "%s\n" "script."
		printf "%s" "Please check that the file \"$1\""
		printf "%s" "exists in the \"$man_src\" and "
 	       	printf "%s\n" "directory."
		printf "%s\n" "Exiting..."
		printf "\n"
		exit "$FAILURE"
	fi
	echo "Done." 
	echo "The manual can now be accessed by typing man \"$2\""
}

install_manpage "build_kernel.1" "build_kernel"
install_manpage "install_manual.1" "install_manual"
install_manpage "config_generator.1" "config_generator"

exit "$SUCCESS"
